# Generated by Django 3.1.7 on 2021-09-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210902_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post.comment'),
        ),
    ]
