# Generated by Django 3.1.7 on 2021-09-15 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replay',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.comment'),
        ),
    ]
